### ISSUE TITLE
Vignettes not working

### ISSUE THREAD

**Issue by agualtieri** [ellieallien/cleaninginspectoR#1]
When running the code: `browseVignettes("cleaninginspectoR")`

The following errors is returned: `No vignettes found by browseVignettes("cleaninginspectoR")`

**Comment by mabafaba** [comment]
Thanks a lot @agualtieri !

try this:
```
remotes::install_github("ellieallien/cleaninginspectoR", build_opts=c())
```
assuming you tried this already, try instead:

```
install.packages("devtools")
devtools::install_github("ellieallien/cleaninginspectoR", build_opts=c())
```
hope that helps?

**Comment by agualtieri** [comment]
Solved! Thanks!

**Comment by mabafaba** [comment]
Thanks.
Will close the issues once it's updated in the vignettes.

**Comment by ellieallien** [comment]
Thanks Martin and Alberto !
